# Generated by Django 5.2.7 on 2025-11-10 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_usertestattempt_useranswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='is_correct',
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('VR', 'Verbal Reasoning'), ('NR', 'Numerical Reasoning'), ('LR', 'Logical Reasoning'), ('SR', 'Spatial Reasoning'), ('MR', 'Memory')], default='LR', max_length=2),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='usertestattempt',
            name='iq_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(default='MC', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.test'),
        ),
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='duration',
            field=models.IntegerField(help_text='Duration in minutes'),
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.usertestattempt'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='selected_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzes.answer'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='text_input',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertestattempt',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
